include.classes=org/apache/solr/core/SolrCore,org/apache/solr/handler/RequestHandlerBase,org/apache/solr/servlet/HttpSolrCall,org/apache/solr/update/CdcrTransactionLog,org/apache/solr/update/DirectUpdateHandler2,org/apache/solr/update/TransactionLog
method.rules=org/apache/solr/core/SolrCore#execute,org/apache/solr/handler/RequestHandlerBase#handleRequest,org/apache/solr/servlet/HttpSolrCall#init,org/apache/solr/update/CdcrTransactionLog#incref,org/apache/solr/update/DirectUpdateHandler2#addDoc,org/apache/solr/update/TransactionLog#incref,org/apache/solr/update/TransactionLog#try_incref
point.entries=org/apache/solr/core/SolrCore#execute(Lorg/apache/solr/request/SolrRequestHandler;Lorg/apache/solr/request/SolrQueryRequest;Lorg/apache/solr/response/SolrQueryResponse;)V,org/apache/solr/update/TransactionLog#incref()V
trace.fields=true
trace.branches=true
coverage.blocks=true
coverage.branches=true
coverage.include.prefixes=org/apache/solr/
target.guard=org/apache/solr/update/TransactionLog#incref()V#B1
target.throw=org/apache/solr/update/TransactionLog#incref()V#L541
adapter.solr.http=true
