include.classes=org/apache/solr/core/SolrCore,org/apache/solr/handler/RequestHandlerBase,org/apache/solr/servlet/HttpSolrCall,org/apache/solr/servlet/SolrRequestParsers$2,org/apache/solr/update/DirectUpdateHandler2
method.rules=org/apache/solr/core/SolrCore#execute,org/apache/solr/handler/RequestHandlerBase#handleRequest,org/apache/solr/servlet/HttpSolrCall#init,org/apache/solr/servlet/SolrRequestParsers$2#read,org/apache/solr/update/DirectUpdateHandler2#addDoc
point.entries=org/apache/solr/core/SolrCore#execute(Lorg/apache/solr/request/SolrRequestHandler;Lorg/apache/solr/request/SolrQueryRequest;Lorg/apache/solr/response/SolrQueryResponse;)V,org/apache/solr/servlet/SolrRequestParsers$2#read()I
trace.fields=true
trace.branches=true
coverage.blocks=true
coverage.branches=true
coverage.include.prefixes=org/apache/solr/
target.guard=org/apache/solr/servlet/SolrRequestParsers$2#read()I#B2
target.throw=org/apache/solr/servlet/SolrRequestParsers$2#read()I#L308
adapter.solr.http=true
