include.classes=org/apache/solr/core/SolrCore,org/apache/solr/handler/RequestHandlerBase,org/apache/solr/search/QueryCommand,org/apache/solr/servlet/HttpSolrCall,org/apache/solr/update/DirectUpdateHandler2
method.rules=org/apache/solr/core/SolrCore#execute,org/apache/solr/handler/RequestHandlerBase#handleRequest,org/apache/solr/search/QueryCommand#setFilter,org/apache/solr/search/QueryCommand#setFilterList,org/apache/solr/servlet/HttpSolrCall#init,org/apache/solr/update/DirectUpdateHandler2#addDoc
point.entries=org/apache/solr/core/SolrCore#execute(Lorg/apache/solr/request/SolrRequestHandler;Lorg/apache/solr/request/SolrQueryRequest;Lorg/apache/solr/response/SolrQueryResponse;)V,org/apache/solr/search/QueryCommand#setFilterList(Ljava/util/List;)Lorg/apache/solr/search/QueryCommand;
trace.fields=true
trace.branches=true
coverage.blocks=true
coverage.branches=true
coverage.include.prefixes=org/apache/solr/
target.guard=org/apache/solr/search/QueryCommand#setFilterList(Ljava/util/List;)Lorg/apache/solr/search/QueryCommand;#B1
target.throw=org/apache/solr/search/QueryCommand#setFilterList(Ljava/util/List;)Lorg/apache/solr/search/QueryCommand;#L83
adapter.solr.http=true
