include.classes=org/apache/zookeeper/ClientCnxn$SendThread,org/apache/zookeeper/ClientCnxnSocketNIO,org/apache/zookeeper/server/FinalRequestProcessor,org/apache/zookeeper/server/NIOServerCnxnFactory,org/apache/zookeeper/server/PrepRequestProcessor,org/apache/zookeeper/server/quorum/UnifiedServerSocket$UnifiedSocket
method.rules=org/apache/zookeeper/ClientCnxn$SendThread#sendPacket,org/apache/zookeeper/ClientCnxnSocketNIO#doIO,org/apache/zookeeper/server/FinalRequestProcessor#processRequest,org/apache/zookeeper/server/NIOServerCnxnFactory#addCnxn,org/apache/zookeeper/server/PrepRequestProcessor#processRequest,org/apache/zookeeper/server/quorum/UnifiedServerSocket$UnifiedSocket#detectMode
point.entries=org/apache/zookeeper/server/NIOServerCnxnFactory#addCnxn(Lorg/apache/zookeeper/server/NIOServerCnxn;)V,org/apache/zookeeper/server/PrepRequestProcessor#processRequest(Lorg/apache/zookeeper/server/Request;)V
trace.fields=true
trace.branches=true
coverage.blocks=true
coverage.branches=true
coverage.include.prefixes=org/apache/zookeeper/
target.guard=org/apache/zookeeper/server/NIOServerCnxnFactory#addCnxn(Lorg/apache/zookeeper/server/NIOServerCnxn;)V#B1
target.throw=org/apache/zookeeper/server/NIOServerCnxnFactory#addCnxn(Lorg/apache/zookeeper/server/NIOServerCnxn;)V#L798
adapter.zookeeper.rpc=true
