include.classes=org/apache/zookeeper/ClientCnxn$SendThread,org/apache/zookeeper/ClientCnxnSocketNIO,org/apache/zookeeper/server/DataTree,org/apache/zookeeper/server/FinalRequestProcessor,org/apache/zookeeper/server/NodeHashMapImpl,org/apache/zookeeper/server/PrepRequestProcessor
method.rules=org/apache/zookeeper/ClientCnxn$SendThread#sendPacket,org/apache/zookeeper/ClientCnxnSocketNIO#doIO,org/apache/zookeeper/server/DataTree#deleteNode,org/apache/zookeeper/server/FinalRequestProcessor#processRequest,org/apache/zookeeper/server/NodeHashMapImpl#clear,org/apache/zookeeper/server/NodeHashMapImpl#put,org/apache/zookeeper/server/NodeHashMapImpl#putWithoutDigest,org/apache/zookeeper/server/PrepRequestProcessor#processRequest
point.entries=org/apache/zookeeper/server/DataTree#deleteNode(Ljava/lang/String;J)V,org/apache/zookeeper/server/PrepRequestProcessor#processRequest(Lorg/apache/zookeeper/server/Request;)V
trace.fields=true
trace.branches=true
coverage.blocks=true
coverage.branches=true
coverage.include.prefixes=org/apache/zookeeper/
target.guard=org/apache/zookeeper/server/DataTree#deleteNode(Ljava/lang/String;J)V#B1
target.throw=org/apache/zookeeper/server/DataTree#deleteNode(Ljava/lang/String;J)V#L558
adapter.zookeeper.rpc=true
